// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAndAddOne() {
  return window['go']['main']['App']['GetAndAddOne']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetPhoto(arg1, arg2) {
  return window['go']['main']['App']['GetPhoto'](arg1, arg2);
}

export function GetPhotoCount(arg1) {
  return window['go']['main']['App']['GetPhotoCount'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenAndSendFile(arg1) {
  return window['go']['main']['App']['OpenAndSendFile'](arg1);
}

export function SendRing(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRing'](arg1, arg2, arg3);
}

export function SendVibrate(arg1, arg2) {
  return window['go']['main']['App']['SendVibrate'](arg1, arg2);
}
