// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Exit():Promise<void>;

export function GetAndAddOne():Promise<number>;

export function GetDevices():Promise<{[key: string]: main.DeviceView}>;

export function GetPhoto(arg1:string,arg2:number):Promise<string>;

export function GetPhotoCount(arg1:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function OpenAndSendFile(arg1:string):Promise<void>;

export function SendRing(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SendVibrate(arg1:string,arg2:number):Promise<void>;
